-- MediKiosk M4.5: ABDM-ready audit foundation.
--
-- Security-sensitive FHIR export activity is recorded in audit_events so a
-- future ABDM integration has a compatible audit trail. The record is
-- deliberately minimal: identifiers and outcome only. It never stores
-- clinical answer contents, document binaries, generated FHIR Bundles,
-- passwords, authentication tokens, CSRF tokens, API keys, or request bodies.

CREATE TABLE IF NOT EXISTS audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR(32)             NOT NULL,
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_username  VARCHAR(100),
    actor_role      VARCHAR(16),
    case_id         VARCHAR(64),
    operation       VARCHAR(32)             NOT NULL,
    resource_type   VARCHAR(32)             NOT NULL,
    outcome         VARCHAR(16)             NOT NULL,
    failure_reason  VARCHAR(128),
    request_path    VARCHAR(255)
);

-- Indexes support the main audit query shapes: time-bounded review,
-- per-actor review, per-case review, and per-event-type counting.
CREATE INDEX IF NOT EXISTS idx_audit_events_occurred_at ON audit_events (occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor ON audit_events (actor_username);
CREATE INDEX IF NOT EXISTS idx_audit_events_case ON audit_events (case_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_type ON audit_events (event_type);