-- MediKiosk M5.2: physician review decisions.
--
-- A physician accept / amend / reject decision for one intake answer of a
-- completed case. The original patient evidence lives unchanged in
-- completed_case_answers; this table stores ONLY the physician's review
-- decision, so the clinical record always preserves:
--
--   source evidence -> physician review decision -> reviewed representation
--
-- The unique (case_id, answer_order) key mirrors the stable pair used by
-- completed_case_answers, so review decisions survive re-persistence of a case
-- and stay aligned with the answering order. Deleting a case cascades to its
-- review entries. No clinical answer content, document binaries, FHIR bundles,
-- or credentials are stored here.

CREATE TABLE IF NOT EXISTS physician_review_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id          VARCHAR(64)             NOT NULL
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    answer_order     INT                     NOT NULL,
    decision         VARCHAR(16)             NOT NULL,
    amended_text     VARCHAR(4000),
    rationale        VARCHAR(1000),
    reviewer_username VARCHAR(100)           NOT NULL,
    decided_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_physician_review_entry_order UNIQUE (case_id, answer_order)
);

CREATE INDEX IF NOT EXISTS idx_physician_review_entries_case
    ON physician_review_entries (case_id);