-- MediKiosk RW2: patient encounters.
--
-- An encounter is the container around a patient visit: starting, resuming,
-- completing intake, and submitting for clinician review. It holds the
-- lifecycle state of the consultation and points at the persisted completed
-- case (the clinical record) once intake is submitted.
--
-- A patient may hold at most one IN_PROGRESS encounter at a time; the account
-- surface enforces that with the partial unique index below (PostgreSQL) and
-- the service double-checks it on every insert, so concurrent starts can never
-- create two active encounters.

CREATE TABLE IF NOT EXISTS encounters (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_user_id BIGINT NOT NULL REFERENCES users (id),
    status         VARCHAR(24) NOT NULL,
    started_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_at   TIMESTAMP WITH TIME ZONE,
    completed_at   TIMESTAMP WITH TIME ZONE,
    case_id        VARCHAR(64),
    notes          VARCHAR(2000),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_encounters_status CHECK (status IN
        ('IN_PROGRESS', 'SUBMITTED', 'UNDER_REVIEW', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_encounters_patient ON encounters (patient_user_id, status);