-- MediKiosk RW2: structured clinical history.
--
-- Every important clinical datum in the patient's longitudinal record
-- carries explicit provenance (who or what produced it). The table is
-- append-oriented: each (patient_user_id, category, concept_key) is
-- unique, so the same intake answer recorded twice is an idempotent
-- upsert. The "current intake" is simply the latest snapshot of the
-- history for the patient, persisted once the intake conversation
-- completes.
--
-- The concept_key field holds a stable, deterministic identifier for
-- the data item: for intake answers it is the question id; for
-- physician-entered items it is a controlled slug; for document-
-- extracted items it is derived from the parser output. This key
-- guarantees determinism across retries, AI rewordings, and resume
-- sequences without guessing or deriving anything from free text.

CREATE TABLE IF NOT EXISTS clinical_history_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_user_id  BIGINT       NOT NULL REFERENCES users (id),
    category         VARCHAR(40)  NOT NULL,
    concept_key      VARCHAR(120) NOT NULL,
    label            VARCHAR(300) NOT NULL,
    value            VARCHAR(4000) NOT NULL,
    note             VARCHAR(2000),
    provenance       VARCHAR(24)  NOT NULL,
    source_label     VARCHAR(200),
    recorded_by      BIGINT       REFERENCES users (id),
    recorded_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_history_patient_category_key
        UNIQUE (patient_user_id, category, concept_key),
    CONSTRAINT ck_history_category CHECK (category IN (
        'CHIEF_COMPLAINT', 'HPI', 'PAST_MEDICAL', 'PAST_SURGICAL',
        'MEDICATIONS', 'ALLERGIES', 'FAMILY', 'PERSONAL_SOCIAL',
        'REVIEW_OF_SYSTEMS', 'DASHAVIDHA', 'AHARA_VIHARA', 'VITALS')),
    CONSTRAINT ck_history_provenance CHECK (provenance IN (
        'PATIENT_REPORTED', 'DOCUMENT_EXTRACTED', 'PHYSICIAN_ENTERED',
        'SYSTEM_GENERATED', 'AI_ASSISTED'))
);

CREATE INDEX IF NOT EXISTS idx_history_patient
    ON clinical_history_items (patient_user_id);
CREATE INDEX IF NOT EXISTS idx_history_patient_category
    ON clinical_history_items (patient_user_id, category);