-- MediKiosk RW2: physician case assignments.
--
-- Assignment controls which physician(s) may view or act on a case. A case
-- with NO assignment is in the unassigned pool (any physician may open it);
-- once one or more physicians are assigned, only those physicians can
-- access the case. This satisfies the requirement that a physician must
-- not automatically see every patient while preserving the read-only
-- backward-compatible pool behaviour for unclaimed cases.
--
-- An admin or the physician may create an assignment (claim); the
-- assignment may be completed (physician accepts the case fully) or
-- unassigned (explicitly released). Deleting a completed case cascades
-- to its assignments via the foreign key.

CREATE TABLE IF NOT EXISTS case_assignments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id            VARCHAR(64) NOT NULL
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    physician_user_id  BIGINT      NOT NULL REFERENCES users (id),
    assigned_by        BIGINT      REFERENCES users (id),
    status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    assigned_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at       TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_case_assign_status CHECK (status IN
        ('ACTIVE', 'COMPLETED', 'UNASSIGNED')),
    CONSTRAINT uq_case_assignment
        UNIQUE (case_id, physician_user_id)
);

CREATE INDEX IF NOT EXISTS idx_case_assign_physician
    ON case_assignments (physician_user_id, status);
CREATE INDEX IF NOT EXISTS idx_case_assign_case
    ON case_assignments (case_id);