-- MediKiosk RW2: completed case status + clinical summaries + consultations.
--
-- completed_cases.status tracks where a case is in the clinical workflow:
--   OPEN       - intake completed, awaiting physician assignment/review
--   IN_REVIEW  - at least one physician is actively reviewing
--   COMPLETED  - clinical record finalized
--
-- A default of 'OPEN' is set to honour all existing rows (RW1 cases are
-- always OPEN; they were created by the legacy intake path and never had a
-- review state beyond the per-answer accept/amend/reject lifecycle).
--
-- clinical_summaries is an editable, per-section clinical summary written
-- by the physician. It may be generated or seeded with AI_ASSISTED content
-- but the physician must explicitly accept/create the final version.
--
-- consultations holds the physician's formal clinical record: their
-- assessment, plan, advice, and follow-up. Both have explicit provenance
-- and status fields, so AI-generated content can never silently become
-- physician-authored content.

ALTER TABLE completed_cases ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'OPEN';
ALTER TABLE completed_cases ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS clinical_summaries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id     VARCHAR(64) NOT NULL
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    section     VARCHAR(24) NOT NULL,
    content     VARCHAR(8000) NOT NULL,
    provenance  VARCHAR(24) NOT NULL,
    status      VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_by  BIGINT REFERENCES users (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_clinical_summary_case_section UNIQUE (case_id, section),
    CONSTRAINT ck_summary_provenance CHECK (provenance IN (
        'PATIENT_REPORTED', 'DOCUMENT_EXTRACTED', 'PHYSICIAN_ENTERED',
        'SYSTEM_GENERATED', 'AI_ASSISTED')),
    CONSTRAINT ck_summary_status CHECK (status IN ('DRAFT', 'ACCEPTED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS consultations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             VARCHAR(64) NOT NULL
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    physician_user_id   BIGINT NOT NULL REFERENCES users (id),
    assessment          TEXT,
    plan                TEXT,
    advice              TEXT,
    follow_up           VARCHAR(1000),
    status              VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    finalized_at        TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_consultation_case UNIQUE (case_id),
    CONSTRAINT ck_consultation_status CHECK (status IN ('DRAFT', 'FINALIZED', 'REJECTED'))
);