-- MediKiosk RW2: red-flag physician assessments + system settings.
--
-- red_flag_assessments records what a physician did about each system-
-- detected or patient-reported red flag. The flag itself is always re-
-- derived deterministically from the patient's own words (never invented
-- by the system); this table captures the human clinical overlay: what
-- the physician noticed, decided, and documented about it.
--
-- system_settings is a lightweight key/value store for runtime-
-- changeable configuration: feature flags, integration toggles, and
-- display preferences that an administrator can adjust without a code
-- deployment. The value is always stored and read as VARCHAR; the
-- application layer interprets it.

CREATE TABLE IF NOT EXISTS red_flag_assessments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id       VARCHAR(64) NOT NULL
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    flag_id       VARCHAR(64) NOT NULL,
    severity      VARCHAR(16) NOT NULL,
    source        VARCHAR(20) NOT NULL,
    assessed_by   BIGINT REFERENCES users (id),
    action        VARCHAR(20) NOT NULL,
    note          VARCHAR(1000),
    assessed_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_flag_case UNIQUE (case_id, flag_id),
    CONSTRAINT ck_flag_assessment_source CHECK (source IN (
        'PATIENT_REPORTED', 'SYSTEM_DETECTED', 'PHYSICIAN_ASSESSMENT')),
    CONSTRAINT ck_flag_assessment_action CHECK (action IN (
        'SEEN', 'ESCALATED', 'CLEARED', 'RESOLVED'))
);

CREATE TABLE IF NOT EXISTS system_settings (
    setting_key    VARCHAR(64) PRIMARY KEY,
    setting_value  VARCHAR(500) NOT NULL,
    description    VARCHAR(500),
    updated_by     BIGINT,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);