-- RD2 Phase 5: patient answer corrections.
--
-- Corrections are ADDITIVE clinical evidence. The original captured answer in
-- completed_case_answers is never modified: a correction stores its own
-- immutable snapshot of the original answer alongside the patient's corrected
-- value, the correcting user, and the correction time. A physician later
-- reviews the correction and decides clinically which value to use; that
-- decision remains a distinct physician-review state (physician_review_entries).
--
-- One current correction per (case_id, answer_order); resubmission replaces the
-- patient's pending correction while the original snapshot is re-verified
-- server-side. This mirrors the (case_id, answer_order) identity used by
-- physician_review_entries and never touches pre-existing migrations.
--
-- The physician's clinical decision is NOT a correction state: it lives in
-- physician_review_entries (audited as PHYSICIAN_REVIEW). status therefore
-- carries exactly one application-written value (SUBMITTED, awaiting
-- physician attention).

CREATE TABLE IF NOT EXISTS patient_answer_corrections (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id          VARCHAR(64)          NOT NULL,
    answer_order     INTEGER              NOT NULL,
    original_answer  VARCHAR(4000)        NOT NULL,
    corrected_answer VARCHAR(4000)        NOT NULL,
    reason           VARCHAR(1000),
    corrected_by     VARCHAR(100)         NOT NULL,
    corrected_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    status           VARCHAR(32)          NOT NULL,
    CONSTRAINT fk_patient_answer_corrections_case FOREIGN KEY (case_id)
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    CONSTRAINT uq_patient_answer_corrections_order UNIQUE (case_id, answer_order),
    CONSTRAINT ck_patient_answer_corrections_status
        CHECK (status IN ('SUBMITTED'))
);

CREATE INDEX IF NOT EXISTS idx_patient_answer_corrections_case
    ON patient_answer_corrections (case_id, answer_order);
