-- MediKiosk Checkpoint 3: consent & patient session schema.

-- Granular, per-purpose consent records. One row per (patient, consent type).
CREATE TABLE IF NOT EXISTS consents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    consent_type  VARCHAR(40)  NOT NULL,
    purpose       VARCHAR(500) NOT NULL,
    state         VARCHAR(20)  NOT NULL,
    granted_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at    TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_consents_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_consents_user_type UNIQUE (user_id, consent_type),
    CONSTRAINT ck_consents_type CHECK (consent_type IN ('CLINICAL_CASE_TAKING', 'AUDIO_CAPTURE', 'DOCUMENT_PROCESSING', 'DATA_SHARING')),
    CONSTRAINT ck_consents_state CHECK (state IN ('GRANTED', 'REVOKED'))
);

CREATE INDEX IF NOT EXISTS idx_consents_user ON consents (user_id);

-- Patient case-taking sessions.
CREATE TABLE IF NOT EXISTS patient_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at  TIMESTAMP WITH TIME ZONE,
    cleared_at    TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_patient_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_patient_sessions_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'EXPIRED'))
);

CREATE INDEX IF NOT EXISTS idx_patient_sessions_user_status ON patient_sessions (user_id, status);
