-- MediKiosk Checkpoint F.4.3: persist completed clinical intake cases.

-- A completed patient intake case, keyed by its stable case identity.
CREATE TABLE IF NOT EXISTS completed_cases (
    case_id    VARCHAR(64) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- The captured clinical answers of a completed case, in answering order.
-- Every field of the original structured answer is preserved verbatim:
-- question id, clinical section, question type, question text, and the raw
-- patient answer. Nothing is summarized or modified here.
CREATE TABLE IF NOT EXISTS completed_case_answers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id       VARCHAR(64)      NOT NULL,
    answer_order  INTEGER          NOT NULL,
    question_id   VARCHAR(64)      NOT NULL,
    section       VARCHAR(32)      NOT NULL,
    question_type VARCHAR(64)      NOT NULL,
    question_text VARCHAR(1000)    NOT NULL,
    answer        VARCHAR(4000)    NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_completed_case_answers_case FOREIGN KEY (case_id)
        REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    CONSTRAINT uq_completed_case_answers_order UNIQUE (case_id, answer_order)
);

CREATE INDEX IF NOT EXISTS idx_completed_case_answers_case
    ON completed_case_answers (case_id, answer_order);