-- M1.1: Link completed cases to patient users and add clinical document support.

-- Link completed cases to the owning patient user.
ALTER TABLE completed_cases
    ADD COLUMN user_id BIGINT NULL;

ALTER TABLE completed_cases
    ADD CONSTRAINT fk_completed_cases_user
        FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX IF NOT EXISTS idx_completed_cases_user
    ON completed_cases (user_id);

-- Clinical documents uploaded by patients against a completed case.
CREATE TABLE IF NOT EXISTS clinical_documents (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id      VARCHAR(64)          NOT NULL UNIQUE,
    case_id          VARCHAR(64)          NOT NULL,
    user_id          BIGINT               NOT NULL,
    original_filename VARCHAR(255)        NOT NULL,
    stored_filename  VARCHAR(64)          NOT NULL,
    content_type     VARCHAR(100)         NOT NULL,
    file_size        BIGINT               NOT NULL,
    uploaded_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_clinical_documents_case
        FOREIGN KEY (case_id) REFERENCES completed_cases (case_id) ON DELETE CASCADE,
    CONSTRAINT fk_clinical_documents_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_clinical_documents_case
    ON clinical_documents (case_id);

CREATE INDEX IF NOT EXISTS idx_clinical_documents_user
    ON clinical_documents (user_id);
