-- M1.3: Persist deterministic structured findings derived from extracted text.
--
-- One findings row per document extraction (1:1). Values that repeat per
-- category (vitals, lab results, medications) live in child tables with a
-- per-category ordering index and the raw source line so every decoded value
-- can be traced back to the original document text.

CREATE TABLE IF NOT EXISTS clinical_document_findings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extraction_id  BIGINT         NOT NULL,
    patient_name   VARCHAR(255),
    patient_dob    VARCHAR(20),
    patient_sex    VARCHAR(20),
    patient_mrn    VARCHAR(64),
    report_date    VARCHAR(20),
    encounter_date VARCHAR(20),
    facility       VARCHAR(255),
    clinician      VARCHAR(255),
    report_type    VARCHAR(255),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_findings_extraction UNIQUE (extraction_id),
    CONSTRAINT fk_findings_extraction
        FOREIGN KEY (extraction_id) REFERENCES clinical_document_extractions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_findings_extraction
    ON clinical_document_findings (extraction_id);

CREATE TABLE IF NOT EXISTS clinical_document_findings_vitals (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    findings_id      BIGINT      NOT NULL,
    vital_type       VARCHAR(30) NOT NULL,
    value            VARCHAR(50) NOT NULL,
    unit             VARCHAR(50),
    source_snippet   VARCHAR(500) NOT NULL,
    occurrence_index INTEGER     NOT NULL,
    CONSTRAINT fk_findings_vitals_findings
        FOREIGN KEY (findings_id) REFERENCES clinical_document_findings (id) ON DELETE CASCADE,
    CONSTRAINT uq_findings_vitals_occurrence UNIQUE (findings_id, occurrence_index)
);

CREATE INDEX IF NOT EXISTS idx_findings_vitals_findings
    ON clinical_document_findings_vitals (findings_id, occurrence_index);

CREATE TABLE IF NOT EXISTS clinical_document_findings_labs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    findings_id      BIGINT       NOT NULL,
    test_name        VARCHAR(120) NOT NULL,
    value            VARCHAR(50)  NOT NULL,
    unit             VARCHAR(60),
    reference_range  VARCHAR(120),
    specimen_date    VARCHAR(20),
    source_snippet   VARCHAR(500) NOT NULL,
    occurrence_index INTEGER      NOT NULL,
    CONSTRAINT fk_findings_labs_findings
        FOREIGN KEY (findings_id) REFERENCES clinical_document_findings (id) ON DELETE CASCADE,
    CONSTRAINT uq_findings_labs_occurrence UNIQUE (findings_id, occurrence_index)
);

CREATE INDEX IF NOT EXISTS idx_findings_labs_findings
    ON clinical_document_findings_labs (findings_id, occurrence_index);

CREATE TABLE IF NOT EXISTS clinical_document_findings_medications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    findings_id      BIGINT       NOT NULL,
    name             VARCHAR(150) NOT NULL,
    strength         VARCHAR(50),
    dose             VARCHAR(50),
    route            VARCHAR(50),
    frequency        VARCHAR(80),
    duration         VARCHAR(80),
    source_snippet   VARCHAR(500) NOT NULL,
    occurrence_index INTEGER      NOT NULL,
    CONSTRAINT fk_findings_medications_findings
        FOREIGN KEY (findings_id) REFERENCES clinical_document_findings (id) ON DELETE CASCADE,
    CONSTRAINT uq_findings_medications_occurrence UNIQUE (findings_id, occurrence_index)
);

CREATE INDEX IF NOT EXISTS idx_findings_medications_findings
    ON clinical_document_findings_medications (findings_id, occurrence_index);